name: HTLogin
version: '${version}'
main: org.howtologin.plugin.HTLogin
api-version: '1.21'
load: STARTUP
authors:
  - HowSberban
description: A login plugin with Paper API.
license: GPL-3.0
folia-supported: true
loader: org.howtologin.plugin.PluginLoaderImpl

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false

permissions:
  htlogin.admin:
    description: 管理员权限
    default: op
